server:
  port: 8330
  forward-headers-strategy: framework
spring:
  application:
    name: nekowindow-service-video
  cloud:
    nacos:
      discovery:
        server-addr: 10.200.0.1:8848
        group: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.200.0.1:3306/nekowindow_video
    username: nekowindow_dev
    password: password
s3:
  endpoint: http://localhost:9000

springdoc:
  swagger-ui:
    path: "/swagger/video/swagger-ui.html"
  api-docs:
    path: "/swagger/video/api-docs"